Repository UKHomeOffice/hocs-cms-data-migrator, pull requests merged in 2023-04, with the labels that each got.

#140 Update README.md
  README.md
Labels: skip-release

#129 HOCS-6248 : able to run the extractors
  helm/hocs-cms-data-migrator/templates/_envs.tpl
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ExtractSelectedComplaintsRunner.java
Labels: patch

#142 HOCS-6301: Remove special chars from document name.
  build.gradle
  src/main/java/uk/gov/digital/ho/hocs/cms/documents/DocumentExtractor.java
Labels: minor

#144 HOCS-6518: Exclude TO and deleted cases.
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintsExtractor.java
  src/test/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintsExtractorTests.java
Labels: minor

#145 HOCS-6582: UKVI Case history PDF failure
  src/main/java/uk/gov/digital/ho/hocs/cms/documents/DocumentCreator.java
Labels: minor, smoketest
