Repository UKHomeOffice/hocs-cms-data-migrator, pull requests merged in 2023-05, with the labels that each got.

#150 HOCS-6616: bug-fix-for-treat-official-individual-conversion
  src/main/java/uk/gov/digital/ho/hocs/cms/treatofficial/TreatOfficialCorrespondentExtractor.java
Labels: minor

#151 HOCS-6615: Set representative id if null.
  src/main/java/uk/gov/digital/ho/hocs/cms/correspondents/CorrespondentExtractor.java
Labels: minor

#162 HOCS-6252: Flyway checksum fixes.
  src/main/resources/db/migration/V1_10__UPDATE_COMPLAINTS_TABLE.sql
  src/main/resources/db/migration/V1_1__CREATE_TABLES.sql
  src/main/resources/db/migration/V1_3__CREATE_CASE_DATA_TABLE.sql
Labels: minor, smoketest

#164 Fix typo in document text
  src/main/java/uk/gov/digital/ho/hocs/cms/documents/DocumentCreator.java
Labels: patch

#165 HOCS-5528: Use closed date.
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintMessageBuilder.java
Labels: minor

#166 Hocs 6426 queuename mapping
  src/main/java/uk/gov/digital/ho/hocs/cms/casedata/QueueNameMapping.java
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintMessageBuilder.java
Labels: minor

#169 HOCS-6266: Create table for linking corresponents to case
  src/main/java/uk/gov/digital/ho/hocs/cms/domain/model/CorrespondentTreatOfficial.java
  src/main/java/uk/gov/digital/ho/hocs/cms/domain/repository/TreatOfficialCorrespondentsRepository.java
  src/main/java/uk/gov/digital/ho/hocs/cms/treatofficial/TreatOfficialCorrespondentExtractor.java
  src/main/resources/db/migration/V1_16__CREATE_CORRESPONDENTS_TREAT_OFFICIALS_TABLE.sql
Labels: minor

#170 [HOCS-6638] Assign HMPO Complex to POGR
  README.md
  src/main/java/uk/gov/digital/ho/hocs/cms/casedata/QueueNameMapping.java
Labels: patch

#172 HOCS-6639: Owning csu may be null
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintsMessageCaseData.java
Labels: minor

#176 Hocs 6136
  src/main/java/uk/gov/digital/ho/hocs/cms/correspondents/CorrespondentExtractor.java
Labels: minor, smoketest

#177 HOCS-6644: Change complaints query
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintsExtractor.java
  src/test/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintsExtractorTests.java
Labels: minor, smoketest

#178 HOCS-6149: Add new fields to message.
  build.gradle
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintMessageBuilder.java
  src/main/java/uk/gov/digital/ho/hocs/cms/complaints/ComplaintsMessageCaseData.java
  src/main/java/uk/gov/digital/ho/hocs/cms/domain/message/CaseDetails.java
  src/test/java/uk/gov/digital/ho/hocs/cms/client/MessageServiceTest.java
  src/test/java/uk/gov/digital/ho/hocs/cms/document/CaseMigrationMessageTest.java
Labels: minor

#180 HOCS-6649: Add extracted fields Severity & Channel to the complaints casedata PDF
  src/main/java/uk/gov/digital/ho/hocs/cms/documents/DocumentCreator.java
Labels: minor
